---
driver:
  name: vagrant

provisioner:
  name: chef_client

platforms:
  - name: centos65
    driver:
      box: "opscode-ubuntu-12.04"
      box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box

suites:
  - name: default
    run_list:
            - recipe[zero::default]
    attributes:
